channels:
  - conda-forge
dependencies:
  - r-base=3.6
  - r-plyr
  - r-stringr
  - r-colorspace
  - r-gtable
  - reshape2
  - r-labeling
  - r-munsell
  - r-yaml
  - r-stringi
  - r-tidyselect
  - r-assertthat
  - r-pkgconfig
  - r-plogr
  - r-ggplot2
  - r-scales
  - r-viridisLite
  - r-htmlwidgets
  - r-tidyr
  - r-hexbin
  - r-RColorBrewer
  - r-dplyr
  - r-tibble
  - r-lazyeval
  - r-crosstalk
  - r-purrr
  - r-data.table
  - r-plotly
  
